name: PDF Watermark Remover

on:
  workflow_dispatch:
    inputs:
      pdf_url:
        description: 'URL of the PDF to remove watermark'
        required: true

jobs:
  remove_watermark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pdfplumber PyPDF2  # Ensures both libraries are installed

    - name: Download PDF from URL
      run: |
        wget -O input_watermarked.pdf "${{ github.event.inputs.pdf_url }}"

    - name: Run watermark remover script
      run: |
        python remove_watermark.py

    - name: Upload output PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: processed-pdf
        path: output_without_watermark.pdf
